### ISSUE TITLE
Missing logmanager dependency

### ISSUE THREAD

**Issue by djarnis73** [wildfly/boms#24]
I'm trying to get at setup going with arquillian and for reasons i have yet to understand i need to have a test dependency on jboss-logmanager in my project.

It would be nice if it could be provided by the bom, but I'm not sure if that is outside the scope of the bom?

**Comment by ctomc** [comment]
You don't need logmanager dependency for testing with arquillian, as tests are executed on server which has all logging in place.

What exactly are you doing that you would need log manager for?

**Comment by djarnis73** [comment]
When invoking the maven failsafe plugin I use (comes from various examples I found and i recall getting various errors and warnings if I don't):
`<java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
`
If I don't add the jboss-logmanager test dependency I get the following stacktrace when running the tests:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running my.ArquillianTest
Could not load Logmanager "org.jboss.logmanager.LogManager"
java.lang.ClassNotFoundException: org.jboss.logmanager.LogManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.util.logging.LogManager$1.run(LogManager.java:195)
        at java.util.logging.LogManager$1.run(LogManager.java:181)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.util.logging.LogManager.<clinit>(LogManager.java:181)
        at java.util.logging.Logger.demandLogger(Logger.java:448)
        at java.util.logging.Logger.getLogger(Logger.java:502)
        at org.jboss.arquillian.core.impl.loadable.LoadableExtensionLoader.<clinit>(LoadableExtensionLoader.java:46)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.jboss.arquillian.test.spi.SecurityActions.loadClass(SecurityActions.java:80)
        at org.jboss.arquillian.test.spi.TestRunnerAdaptorBuilder.build(TestRunnerAdaptorBuilder.java:50)
        at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:113)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```
The test does not fail but i dislike having stacktrace.

**Comment by djarnis73** [comment]
Ok, it works when running without java.util.logging.manager=org.jboss.logmanager.LogManager.

I think that was required when I experimented with running in embedded mode, but embedded mode seems broken for wildfly 10.

**Comment by ctomc** [comment]
Yes you could use jboss logmanager for also for your client tests (not running on wildfly instance)
But that is not needed, it would be needed for writing some deep integration with wildfly (like subsystem) but for all other cases it is just impl detail.

Embedded is story on its own, I would suggest using managed arquillian container as that is the only proper way to be sure your code will work 100% the same on real wildfly.
